### ISSUE TITLE
How to run the app?

### ISSUE THREAD

**Issue by daldr-ntml** [miguelgrinberg/flask-gridjs#11]
Hi, please will you explain the correct commands to run this app?  I am seeing:

```
(microblog_venv) flask-gridjs-main> $Env:FLASK_APP="create_fake_users.py"
(microblog_venv) flask-gridjs-main> py create_fake_users.py 100
Traceback (most recent call last):
  File "C:\Users\<snip>\flask-gridjs-main\create_fake_users.py", line 4, in <module>
    from basic_table import db, User
  File "C:\Users\<snip>\flask-gridjs-main\basic_table.py", line 19, in <module>
    db.create_all()
  <snip>
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
```

**Comment by miguelgrinberg** [comment]
Are you using the dependencies listed in the requirements.txt file? This error makes me think that you are using different (likely newer) dependencies.

**Comment by daldr-ntml** [comment]
Thank you, I was using a venv created for the Flask mega-tutorial. Switching to one created from requirements.txt fixed the problem.
