### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by karthikmurugadoss** [miguelgrinberg/flask-gridjs#5]
Steps to reproduce:
1. Clone the repo
2. Set up python3.9 environment
3. pip install the requirements
4. Run `python basic_table.py`

I get the following error:
``` * Serving Flask app 'basic_table' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/temp/web_spreadsheet/flask-gridjs/basic_table.py", line 29, in <module>
    app.run()
  File "/home/temp/web_spreadsheet/venv/lib/python3.9/site-packages/flask/app.py", line 922, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/temp/web_spreadsheet/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 1008, in run_simple
    inner()
  File "/home/temp/web_spreadsheet/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 948, in inner
    srv = make_server(
  File "/home/temp/web_spreadsheet/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 780, in make_server
    return ThreadedWSGIServer(
  File "/home/temp/web_spreadsheet/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 686, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/home/temp/miniconda3/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/temp/miniconda3/lib/python3.9/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/temp/miniconda3/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

I don't have anything running on port 5000 and I also checked multiple other ports using the `-p` parameter

**Comment by miguelgrinberg** [comment]
Is this a problem specifically with this one application? Or with all Flask applications? Because I don't see how this can be an issue with my app.

**Comment by karthikmurugadoss** [comment]
Yes I think it was an issue with the version of Flask that I was using.

Upon upgrading that, the app started to work

Thanks!
